# Additional Falco rule files.
# Keys are file names and values are full rule file contents.
# They will be mounted to /etc/falco/rules.d/<file-name>.
# Falco default rules remain enabled; custom rules are loaded in addition.
# Built-in test rule enabled by default.
# demo
#- rule: Test - Terminal Shell In Container
#  desc: Test rule to validate Falco custom rules pipeline
#  condition: container and shell_procs and proc.name in (bash, sh, zsh)
#  output: >
#    TEST custom rule matched (user=%user.name command=%proc.cmdline container=%container.id image=%container.image.repository)
#  priority: WARNING
#  tags: [container, test]
customRules: {}

# Disable built-in Falco rules by name.
# Example:
# disabledRules:
#   - Terminal shell in container
#   - Write below etc
disabledRules: []
