{{- $oe := .Values.olaresEnv | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cmproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ index $oe "OPENAI_API_KEY" | default "sk-xxxxx" | quote }}
  MJ_API_SECRET: {{ index $oe "MJ_API_SECRET" | default "your-mj-api-secret" | quote }}
  LUMA_KEY: {{ index $oe "LUMA_KEY" | default "your-luma-key" | quote }}
  SUNO_KEY: {{ index $oe "SUNO_KEY" | default "your-suno-key" | quote }}
