apiVersion: v1
kind: Secret
metadata:
  name: dify-api-secrets
  namespace: '{{ .Release.Namespace }}'
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  CELERY_BROKER_URL: {{ printf "redis://:%s@redis:6379/0" .Values.redis.password | quote }}
  CELERY_BROKER_URL_DB1: {{ printf "redis://:%s@redis:6379/1" .Values.redis.password | quote }}
  SMTP_PASSWORD: {{ .Values.olaresEnv.SMTP_PASSWORD | default "password" | quote }}
  SECRET_KEY: "olares-difyv3-secret-key-please-rotate-42"
  PGVECTOR_PASSWORD: {{ .Values.postgres.password | quote }}
  PGVECTOR_POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  PGVECTO_RS_PASSWORD: {{ .Values.postgres.password | quote }}
  WEAVIATE_API_KEY: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
  WEAVIATE_AUTHENTICATION_APIKEY_ALLOWED_KEYS: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
  CODE_EXECUTION_API_KEY: "dify-sandbox"
  SANDBOX_API_KEY: "dify-sandbox"
  INNER_API_KEY_FOR_PLUGIN: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
  DIFY_INNER_API_KEY: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
  PLUGIN_DIFY_INNER_API_KEY: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
  PLUGIN_DAEMON_KEY: "lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi"
  SERVER_KEY: "lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi"
  ALIYUN_OSS_ACCESS_KEY: "your-access-key"
  ALIYUN_OSS_SECRET_KEY: "your-secret-key"
  ANALYTICDB_KEY_SECRET: "your-sk"
  ANALYTICDB_NAMESPACE_PASSWORD: "difypassword"
  ANALYTICDB_PASSWORD: "testpassword"
  AZURE_BLOB_ACCOUNT_KEY: "difyai"
  BAIDU_OBS_ACCESS_KEY: "your-access-key"
  BAIDU_OBS_SECRET_KEY: "your-secret-key"
  BAIDU_VECTOR_DB_API_KEY: "dify"
  CHROMA_AUTH_CREDENTIALS: ""
  CHROMA_SERVER_AUTHN_CREDENTIALS: "difyai123456"
  COUCHBASE_PASSWORD: "password"
  ELASTICSEARCH_PASSWORD: "elastic"
  HUAWEI_CLOUD_PASSWORD: "admin"
  HUAWEI_OBS_ACCESS_KEY: "your-access-key"
  HUAWEI_OBS_SECRET_KEY: "your-secret-key"
  INIT_PASSWORD: ""
  LINDORM_PASSWORD: "lindorm"
  MILVUS_PASSWORD: "Milvus"
  MILVUS_TOKEN: ""
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  MYSCALE_PASSWORD: ""
  NOTION_CLIENT_SECRET: ""
  NOTION_INTERNAL_SECRET: ""
  OCEANBASE_VECTOR_PASSWORD: "difyai123456"
  OCI_ACCESS_KEY: "your-access-key"
  OCI_SECRET_KEY: "your-secret-key"
  OPENGAUSS_PASSWORD: "Dify@123"
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "Qazwsxedc!@#123"
  OPENSEARCH_PASSWORD: "admin"
  ORACLE_PASSWORD: "dify"
  ORACLE_WALLET_PASSWORD: "dify"
  OTLP_API_KEY: ""
  PLUGIN_ALIYUN_OSS_ACCESS_KEY_ID: ""
  PLUGIN_ALIYUN_OSS_ACCESS_KEY_SECRET: ""
  PLUGIN_AWS_ACCESS_KEY: ""
  PLUGIN_AWS_SECRET_KEY: ""
  PLUGIN_TENCENT_COS_SECRET_ID: ""
  PLUGIN_TENCENT_COS_SECRET_KEY: ""
  PLUGIN_VOLCENGINE_TOS_ACCESS_KEY: ""
  PLUGIN_VOLCENGINE_TOS_SECRET_KEY: ""
  POSTGRES_PASSWORD: ""
  QDRANT_API_KEY: "difyai123456"
  RELYT_PASSWORD: "difyai123456"
  RESEND_API_KEY: "your-resend-api-key"
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""
  SUPABASE_API_KEY: "your-access-key"
  TABLESTORE_ACCESS_KEY_ID: "xxx"
  TABLESTORE_ACCESS_KEY_SECRET: "xxx"
  TENCENT_COS_SECRET_ID: "your-secret-id"
  TENCENT_COS_SECRET_KEY: "your-secret-key"
  TENCENT_VECTOR_DB_API_KEY: "dify"
  TIDB_ON_QDRANT_API_KEY: "dify"
  TIDB_PRIVATE_KEY: "dify"
  TIDB_VECTOR_PASSWORD: ""
  UNSTRUCTURED_API_KEY: ""
  UPSTASH_VECTOR_TOKEN: "dify"
  VASTBASE_PASSWORD: "Difyai123456"
  VIKINGDB_ACCESS_KEY: "your-ak"
  VIKINGDB_SECRET_KEY: "your-sk"
  VOLCENGINE_TOS_ACCESS_KEY: "your-access-key"
  VOLCENGINE_TOS_SECRET_KEY: "your-secret-key"
