apiVersion: v1
kind: Secret
metadata:
  name: dify-api-secrets
  namespace: '{{ .Release.Namespace }}'
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  CELERY_BROKER_URL: {{ printf "redis://:%s@redis:6379/0" .Values.redis.password | quote }}
  CELERY_BROKER_URL_DB1: {{ printf "redis://:%s@redis:6379/1" .Values.redis.password | quote }}
  SMTP_PASSWORD: {{ .Values.olaresEnv.SMTP_PASSWORD | default "password" | quote }}
  SECRET_KEY: "olares-difyv3-secret-key-please-rotate-42"
  PGVECTOR_PASSWORD: {{ .Values.postgres.password | quote }}
  PGVECTOR_POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  PGVECTO_RS_PASSWORD: {{ .Values.postgres.password | quote }}
  WEAVIATE_API_KEY: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
  WEAVIATE_AUTHENTICATION_APIKEY_ALLOWED_KEYS: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
  CODE_EXECUTION_API_KEY: "dify-sandbox"
  SANDBOX_API_KEY: "dify-sandbox"
  INNER_API_KEY_FOR_PLUGIN: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
  DIFY_INNER_API_KEY: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
  PLUGIN_DIFY_INNER_API_KEY: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
  PLUGIN_DAEMON_KEY: "lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi"
  SERVER_KEY: "lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi"
