apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: wewerss
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  DATABASE_URL: 'mysql://{{ .Values.mysql.username }}:{{ .Values.mysql.password}}@{{ .Values.mysql.host }}:3306/{{ .Values.mysql.databases.wewe_rss }}?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30'
  DB_ROOT_PASSWORD: {{ .Values.mysql.password | quote }}
