apiVersion: v2
name: neodb
description: NeoDB is an open source project to help users manage, share and discover collections, reviews and ratings for cultural products in the Fediverse.
type: application
version: 1.0.6
appVersion: "0.19.6.3"
