image:
  neodb:
    repository: docker.io/neodb/neodb
    tag: "0.19.6.3"
    pullPolicy: IfNotPresent
  typesense:
    repository: docker.io/typesense/typesense
    tag: "26.0"
    pullPolicy: IfNotPresent
  busybox:
    repository: docker.io/beclab/aboveos-busybox
    tag: "1.37.0"
    pullPolicy: IfNotPresent

postgres:
  host: postgres
  port: "5432"
  username: neodb
  password: neodb
  databases:
    neodb: neodb
    takahe: takahe

redis:
  host: redis
  port: "6379"
  password: ""

appSecret: "7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e"
typesenseApiKey: "neodb_typesense_api_key_secret"
siteName: "NeoDB"

workloads:
  neodb:
    replicaCount: 1

resources:
  nginx:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi
  web:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  takahe:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 384Mi
  worker:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 384Mi
  stator:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  typesense:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
