image:
  repository: tautulli/tautulli
  tag: v2.17.1
  pullPolicy: IfNotPresent

env:
  tz: Europe/Madrid
  puid: "1000"
  pgid: "1000"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

userspace:
  appData: /Data/studio/tautulli
