{{- $fastgptDomainENV := split "," .Values.domain.fastgpt -}}
{{- $fastgptDomain := index $fastgptDomainENV "_0" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastgpt-config
  namespace: {{ .Release.Namespace }}
data:
  HOSTNAME: "0.0.0.0"
  FE_DOMAIN: "https://{{ $fastgptDomain }}"
  DEFAULT_ROOT_PSW: "{{ .Values.olaresEnv.DEFAULT_ROOT_PSW }}"
  AES256_SECRET_KEY: "fastgptsecret"
  AIPROXY_API_ENDPOINT: "http://aiproxy-service:3000"
  PLUGIN_BASE_URL: "http://plugin-service:3000"
  CODE_SANDBOX_URL: "http://sandbox-service:3000"
  DB_MAX_LINK: "30"
  MONGODB_URI: "mongodb://fastgpt:fastgpt@mongo-service:27017/fastgpt?authSource=admin&directConnection=true"
  PG_URL: "postgresql://fastgpt:fastgpt@localhost:5432/postgres"
  REDIS_URL: "redis://redis-svc:6379"
  STORAGE_VENDOR: "minio"
  STORAGE_REGION: "us-east-1"
  STORAGE_ACCESS_KEY_ID: "minioadmin"
  STORAGE_SECRET_ACCESS_KEY: "minioadmin"
  STORAGE_PUBLIC_BUCKET: "fastgpt-public"
  STORAGE_PRIVATE_BUCKET: "fastgpt-private"
  STORAGE_S3_ENDPOINT: "http://minio-service:9000"
  STORAGE_S3_FORCE_PATH_STYLE: "true"
  STORAGE_S3_MAX_RETRIES: "3"
  STORAGE_EXTERNAL_ENDPOINT: "http://minio-service:9000"
  SYNC_INDEX: "1"
  WORKFLOW_MAX_RUN_TIMES: "1000"
  WORKFLOW_MAX_LOOP_TIMES: "100"
  USE_IP_LIMIT: "false"
  CHECK_INTERNAL_IP: "false"
  LOG_ENABLE_CONSOLE: "true"
  LOG_CONSOLE_LEVEL: "warning"
  LOG_ENABLE_OTEL: "false"
