---
apiVersion: v1
kind: Secret
metadata:
  name: fastgpt-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AIPROXY_API_TOKEN: "aiproxy"
  PLUGIN_TOKEN: "token"
  CODE_SANDBOX_TOKEN: "codesandbox"
  TOKEN_KEY: "olares"
  ROOT_KEY: "olares"
  FILE_TOKEN_KEY: "olares"
