---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: n8n
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: {{ .Release.Namespace }}
  labels:
    app: n8n
spec:
  replicas: {{ .Values.workloads.n8n.replicaCount }}
  selector:
    matchLabels:
      app: n8n
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-chown-data
          image: beclab/aboveos-busybox:1.37.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /data
          volumeMounts:
            - mountPath: /data
              name: n8n-config
      volumes:
        - name: n8n-config
          hostPath:
            type: DirectoryOrCreate
            {{- if .Values.sysVersion }}
              {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: {{ .Values.userspace.appData }}/
              {{- else }}
            path: {{ .Values.userspace.appData }}/n8n/
              {{- end }}
            {{- else }}
            path: {{ .Values.userspace.appData }}/n8n/
            {{- end }}
      containers:
        - name: n8n
          image: "docker.io/n8nio/n8n:2.27.5"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 3000m
              memory: 6Gi
          ports:
            - containerPort: 5678
          envFrom:
            - configMapRef:
                name: n8n-config
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: n8n-config
