
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentzero
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: agentzero
spec:
  replicas: {{ .Values.workloads.agentzero.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: agentzero
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: agentzero
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: agentzero
          image: docker.io/beclab/agent0ai-agent-zero:v1.15
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 2
              memory: 2Gi
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: agentzero-data
              mountPath: /a0/usr
              subPath: usr
          startupProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /api/health
              port: 80
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

      restartPolicy: Always
      volumes:
        - name: agentzero-data
          hostPath:
            type: DirectoryOrCreate
            path: '{{ .Values.userspace.appData }}'

---
apiVersion: v1
kind: Service
metadata:
  name: agentzero
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: agentzero
spec:
  ports:
    - name: az-port
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: agentzero
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: agentzero-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: agentzero
spec:
  ports:
    - name: mcp-port
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: agentzero
status:
  loadBalancer: {}
