apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinity
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.workloads.infinity.replicaCount }}
  selector:
    matchLabels:
      app: infinity
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: infinity
    spec:
      initContainers:
      - name: init-chmod-data
        image: "docker.io/beclab/aboveos-busybox:1.37.0"
        command:
          - sh
          - '-c'
          - |
            chown -R 1000:1000 /appcache /var/infinity
        resources: {}
        volumeMounts:
          - name: appcache
            mountPath: /appcache
          - name: infinity-data
            mountPath: /var/infinity
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
      containers:
      - name: infinity
        image: "docker.io/infiniflow/infinity:v0.7.0"
        args: ["-f", "/infinity_conf.toml"]
        ports:
        - containerPort: 23820
        - containerPort: 23817
        - containerPort: 5432
        env:
        - name: TZ
          value: "Asia/Shanghai"
        volumeMounts:
        - name: infinity-data
          mountPath: /var/infinity
        - name: infinity-config
          mountPath: /infinity_conf.toml
          subPath: infinity_conf.toml
        resources:
          limits:
            cpu: "1"
            memory: 2000Mi
          requests:
            cpu: 50m
            memory: 512Mi
      volumes:
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appCache }}'
            {{- else }}
          path: '{{ .Values.userspace.appCache }}/ragflow'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appCache }}/ragflow'
          {{- end }}
          type: DirectoryOrCreate
        name: appcache
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appCache }}/infinity'
            {{- else }}
          path: '{{ .Values.userspace.appCache }}/ragflow/infinity'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appCache }}/ragflow/infinity'
          {{- end }}
          type: DirectoryOrCreate
        name: infinity-data
      - name: infinity-config
        configMap:
          name: infinity-config
---
apiVersion: v1
kind: Service
metadata:
  name: infinity
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 23820
    targetPort: 23820
  - name: thrift
    port: 23817
    targetPort: 23817
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: infinity
