apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragflow
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.workloads.ragflow.replicaCount }}
  selector:
    matchLabels:
      app: ragflow
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ragflow
    spec:
      initContainers:
      - name: init-chmod-data
        image: "docker.io/beclab/aboveos-busybox:1.37.0"
        command:
          - sh
          - '-c'
          - |
            chown -R 1000:1000 /appcache /ragflow/logs
        resources: {}
        volumeMounts:
          - name: appcache
            mountPath: /appcache
          - name: ragflow-logs
            mountPath: /ragflow/logs
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
      containers:
      - name: ragflow
        image: "docker.io/infiniflow/ragflow:v0.26.1"
        args:
          - --enable-adminserver
        ports:
        - containerPort: 9380
        - containerPort: 9381
        - containerPort: 80
        env:
        - name: HF_ENDPOINT
          value: '{{ .Values.olaresEnv.HF_ENDPOINT }}'
        - name: MACOS
          value: '0'
        - name: API_PROXY_SCHEME
          value: 'python'
        - name: DOC_ENGINE
          value: 'elasticsearch'
        - name: MYSQL_PORT
          value: "{{ .Values.mysql.port }}"
        - name: MYSQL_HOST
          value: "{{ .Values.mysql.host }}"
        - name: MYSQL_USER
          value: "{{ .Values.mysql.username }}"
        - name: MYSQL_PASSWORD
          value: "{{ .Values.mysql.password }}"
        - name: MYSQL_DBNAME
          value: "{{ .Values.mysql.databases.rag_flow }}"
        - name: ES_HOST
          value: 'es01'
        - name: ELASTIC_PASSWORD
          value: 'infini_rag_flow'
        - name: REDIS_HOST
          value: 'redis'
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_PASSWORD
          value: 'infini_rag_flow'
        - name: MINIO_HOST
          value: 'minio'
        - name: MINIO_PORT
          value: '9000'
        - name: MINIO_USER
          value: 'rag_flow'
        - name: MINIO_PASSWORD
          value: 'infini_rag_flow'
        resources:
          limits:
            cpu: "4"
            memory: 10Gi
          requests:
            cpu: "1"
            memory: 1Gi
        startupProbe:
          httpGet:
            path: /api/v1/system/healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 60
        readinessProbe:
          httpGet:
            path: /api/v1/system/healthz
            port: 80
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/system/ping
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 5
        volumeMounts:
          - name: ragflow-logs
            mountPath: /ragflow/logs
      volumes:
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appCache }}'
            {{- else }}
          path: '{{ .Values.userspace.appCache }}/ragflow'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appCache }}/ragflow'
          {{- end }}
          type: DirectoryOrCreate
        name: appcache
      - hostPath:
          {{- if .Values.sysVersion }}
            {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
          path: '{{ .Values.userspace.appCache }}/ragflow'
            {{- else }}
          path: '{{ .Values.userspace.appCache }}/ragflow/ragflow'
            {{- end }}
          {{- else }}
          path: '{{ .Values.userspace.appCache }}/ragflow/ragflow'
          {{- end }}
          type: DirectoryOrCreate
        name: ragflow-logs
---
apiVersion: v1
kind: Service
metadata:
  name: ragflow
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ragflow
