apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ragflow
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  ELASTIC_PASSWORD: "infini_rag_flow"
  REDIS_PASSWORD: "infini_rag_flow"
  MINIO_PASSWORD: "infini_rag_flow"
