apiVersion: v1
kind: Service
metadata:
  name: ticket-bff-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: ticket-bff
spec:
  selector:
    app: ticket-bff
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
