apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: lares-router-catalog-nats
  namespace: {{ .Release.Namespace }}
spec:
  app: lares
  appNamespace: router
  middleware: nats
  nats:
    user: {{ printf "%s-lares-catalog" .Release.Namespace | quote }}
    password:
      valueFrom:
        secretKeyRef:
          name: lares-nats
          key: password
    subjects:
      - name: catalog
        permission:
          pub: deny
          sub: allow
