---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: {{ .Release.Namespace }}
data:
  pipeline_config_fastdeploy.yaml: |
    pipeline_name: PaddleOCR-VL-1.5

    batch_size: 1

    use_queues: True

    use_doc_preprocessor: False
    use_layout_detection: True
    use_chart_recognition: False
    use_seal_recognition: False
    format_block_content: False
    merge_layout_blocks: True
    markdown_ignore_labels:
      - number
      - footnote
      - header
      - header_image
      - footer
      - footer_image
      - aside_text

    SubModules:
      LayoutDetection:
        module_name: layout_detection
        model_name: PP-DocLayoutV3
        model_dir: null
        batch_size: 8
        threshold: 0.1
        layout_nms: True
        layout_unclip_ratio: [1.2, 1.2]
        layout_merge_bboxes_mode:
          0: "union"
          1: "union"
          2: "union"
          3: "large"
          4: "union"
          5: "large"
          6: "large"
          7: "union"
          8: "union"
          9: "union"
          10: "union"
          11: "union"
          12: "union"
          13: "union"
          14: "union"
          15: "large"
          16: "union"
          17: "large"
          18: "union"
          19: "union"
          20: "union"
          21: "union"
          22: "union"
          23: "union"
          24: "union"
      VLRecognition:
        module_name: vl_recognition
        model_name: PaddleOCR-VL-1.5-0.9B
        model_dir: null
        batch_size: 512

    SubPipelines:
      DocPreprocessor:
        pipeline_name: doc_preprocessor
        batch_size: 8
        use_doc_orientation_classify: True
        use_doc_unwarping: True
        SubModules:
          DocOrientationClassify:
            module_name: doc_text_orientation
            model_name: PP-LCNet_x1_0_doc_ori
            model_dir: null
            batch_size: 8
          DocUnwarping:
            module_name: image_unwarping
            model_name: UVDoc
            model_dir: null
