{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
{{- $hfService := .Values.olaresEnv.OLARES_USER_HUGGINGFACE_SERVICE | default "https://huggingface.co" }}
{{- $hfEndpoint := $hfService | trimSuffix "/" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-env
  namespace: "{{ .Release.Namespace }}"
data:
  PGID: "1000"
  PUID: "1000"
  TZ: "Etc/UTC"
  GGML_CUDA_DISABLE_GRAPHS: "1"
  OLLAMA_ORIGINS: "*"
  OLLAMA_DEBUG: "1"
  MODEL_NAME: "gemma4:31b-it-ud-q4_K_XL"
  HF_REPO: "unsloth/gemma-4-31B-it-GGUF"
  HF_FILE: "gemma-4-31B-it-UD-Q4_K_XL.gguf"
  HF_ENDPOINT: "{{ $hfEndpoint }}"
  GGUF_DIR: "/models"
  GGUF_PARAMS: '{}'
  GGUF_TEMPLATE_NAME: "gemma4"
  OLLAMA_CONTEXT_LENGTH: "32768"
  OLLAMA_REPEAT_PENALTY: "1.0"
  OLLAMA_REPEAT_LAST_N: "128"
  OLLAMA_NUM_PARALLEL: "1"
  OLLAMA_FLASH_ATTENTION: "1"
  OLLAMA_KV_CACHE_TYPE: "q8_0"
  MODELFILE_B64: "RlJPTSAvbW9kZWxzL2dlbW1hLTQtMzFCLWl0LVVELVE0X0tfWEwuZ2d1ZgoKUEFSQU1FVEVSIG51bV9jdHggMzI3NjgK"
{{- end }}
