workloads:
  nuq-worker:
    replicaCount: 1
  worker:
    replicaCount: 1
  firecrawl-redis:
    replicaCount: 1
  playwright-service:
    replicaCount: 1
  nuq-postgres:
    replicaCount: 1
  firecrawl-api:
    replicaCount: 1
  firecrawl:
    replicaCount: 1
