apiVersion: v2
name: fastnotesync
description: Fast Note Sync Service is a self-hosted platform designed for real-time synchronization of Obsidian notes.
type: application
version: 1.0.1
appVersion: "3.5.1"
