workloads:
  plane-api:
    replicaCount: 1
  plane-live:
    replicaCount: 1
  plane-space:
    replicaCount: 1
  plane-admin:
    replicaCount: 1
  plane:
    replicaCount: 1
  plane-proxy:
    replicaCount: 1
