---
apiVersion: v1
kind: Service
metadata:
  name: penpot-mcp
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: penpot-mcp
  ports:
    - name: plugin
      port: 4400
      targetPort: 4400
      protocol: TCP
    - name: mcp-http
      port: 4401
      targetPort: 4401
      protocol: TCP
    - name: mcp-ws
      port: 4402
      targetPort: 4402
      protocol: TCP
