apiVersion: v2
name: triliumnext
description: TriliumNext is a personal knowledge base with hierarchically structured notes, rich text editor, note linking, scripting, and more.
type: application
version: 1.0.0
appVersion: "0.103.0"
