apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  FRIGATE_RTSP_PASSWORD: {{ .Values.rtspPassword | default "frigate" | quote }}
