apiVersion: v2
name: vaultwarden
description: Vaultwarden is an alternative Bitwarden compatible server written in Rust, compatible with upstream Bitwarden clients.
type: application
version: 1.0.2
appVersion: "1.36.0"
