apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollamaniemotron3nano30ba3b.fullname" . }}
  labels:
    {{- include "ollamaniemotron3nano30ba3b.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "ollamaniemotron3nano30ba3b.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ollamaniemotron3nano30ba3b.fullname" . }}
  labels:
    {{- include "ollamaniemotron3nano30ba3b.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ollamaniemotron3nano30ba3b.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ollamaniemotron3nano30ba3b.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ollamaniemotron3nano30ba3b.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PROXY_PORT
              value: "8080"
            - name: OLLAMA_API_HOST
              value: "{{ include "ollamaniemotron3nano30ba3bserver.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
            - name: OLLAMA_API_PORT
              value: "11434"
            - name: HUGGINGFACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "ollamaniemotron3nano30ba3b.fullname" . }}-secret
                  key: HF_TOKEN
            - name: HUGGINGFACE_SERVICE
              valueFrom:
                secretKeyRef:
                  name: {{ include "ollamaniemotron3nano30ba3b.fullname" . }}-secret
                  key: HF_SERVICE
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ollamaniemotron3nano30ba3b.fullname" . }}-secret
type: Opaque
data:
  HF_TOKEN: {{ .Values.OLARES_USER_HUGGINGFACE_TOKEN | b64enc }}
  HF_SERVICE: {{ .Values.OLARES_USER_HUGGINGFACE_SERVICE | b64enc }}