apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollamaniemotron3nano30ba3bserver.fullname" . }}
  labels:
    {{- include "ollamaniemotron3nano30ba3bserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: ollama-api
  selector:
    {{- include "ollamaniemotron3nano30ba3bserver.selectorLabels" . | nindent 4 }}