apiVersion: v2
appVersion: '0.30.4'
description: NVIDIA Nemotron-3-Nano 30B A3B (Ollama) - Mixture-of-Experts model optimized for agentic AI workflows on NVIDIA RTX GPUs
name: ollamaniemotron3nano30ba3b
type: application
version: '1.0.0'