# Default values for ollamaniemotron3nano30ba3b

# Admin user configuration
admin: ""
bfl: 
  username: ""

# Environment variables
KEEP_ALIVE: false
OLARES_USER_HUGGINGFACE_TOKEN: ""
OLARES_USER_HUGGINGFACE_SERVICE: ""

# Olares system values (these will be set by the system)
olaresEnv: {}