apiVersion: v1
kind: Service
metadata:
  name: homeassistant-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      name: ha-service
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: ha-proxy
