apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: miniflux
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  ADMIN_PASSWORD: {{ .Values.olaresEnv.ADMIN_PASSWORD | quote }}
  DATABASE_URL: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:5432/{{ .Values.postgres.databases.miniflux }}"
