{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" .Release.Name)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: medusa
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:5432/{{ .Values.postgres.databases.medusa }}"
  PGPASSWORD: {{ .Values.postgres.password | quote }}
  ADMIN_PASSWORD: {{ .Values.olaresEnv.ADMIN_PASSWORD | quote }}
  JWT_SECRET: {{ if and $existingSecret (index $existingSecret.data "JWT_SECRET") -}}
    {{- index $existingSecret.data "JWT_SECRET" | b64dec -}}
  {{- else -}}
    {{- randAlphaNum 32 -}}
  {{- end }}
  COOKIE_SECRET: {{ if and $existingSecret (index $existingSecret.data "COOKIE_SECRET") -}}
    {{- index $existingSecret.data "COOKIE_SECRET" | b64dec -}}
  {{- else -}}
    {{- randAlphaNum 32 -}}
  {{- end }}
