{{- $mattermostDomainENV := split  ","  .Values.domain.mattermost -}}
{{- $mattermostDomain := index $mattermostDomainENV "_0" -}}
{{- $pgDatasource := printf "postgres://%s:%s@%s:%v/%s?sslmode=disable&connect_timeout=10" .Values.postgres.username .Values.postgres.password .Values.postgres.host .Values.postgres.port .Values.postgres.databases.mattermost -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mattermost
  name: mattermost
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.workloads.mattermost.replicaCount }}
  strategy: 
    type: Recreate
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      io.kompose.service: mattermost
  template:
    metadata:
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: mattermost
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: init-chmod-data
        image: "docker.io/beclab/aboveos-busybox:1.37.0"
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        command:
          - sh
          - '-c'
          - |
            chown -R 1000:1000 /mattermost/config /mattermost/data /mattermost/plugins /mattermost/client/plugins
        volumeMounts:
        - mountPath: /mattermost/config
          name: mattermost-config
        - mountPath: /mattermost/data
          name: mattermost-data
        - mountPath: /mattermost/plugins
          name: mattermost-server-plugins
        - mountPath: /mattermost/client/plugins
          name: mattermost-plugins
      containers:
      - name: mattermost
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Etc/UTC
        - name: MM_SQLSETTINGS_DRIVERNAME
          value: postgres
        - name: MM_SQLSETTINGS_DATASOURCE
          value: {{ $pgDatasource | quote }}
        - name: MM_SERVICESETTINGS_SITEURL
          value: https://{{ $mattermostDomain }}
        - name: MM_TEAMSETTINGS_SITENAME
          value: Mattermost in Olares
        - name: MM_LOGSETTINGS_ENABLEFILE
          value: "false"
        envFrom:
        - secretRef:
            name: mattermost-team-edition-config
        ports:
        - name: http
          containerPort: 8065
          protocol: TCP
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          httpGet:
            path: /healthz
            port: http
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 5
          httpGet:
            path: /api/v4/system/ping
            port: http
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          httpGet:
            path: /api/v4/system/ping
            port: http
        volumeMounts:
        - mountPath: /mattermost/config
          name: mattermost-config
        - mountPath: /mattermost/data
          name: mattermost-data
        - mountPath: /mattermost/plugins
          name: mattermost-server-plugins
        - mountPath: /mattermost/client/plugins
          name: mattermost-plugins
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 4Gi
      volumes:
      - hostPath:
          path: '{{ .Values.userspace.appData }}/mattermost/config'
          type: DirectoryOrCreate
        name: mattermost-config
      - hostPath:
          path: '{{ .Values.userspace.appData }}/mattermost/data'
          type: DirectoryOrCreate
        name: mattermost-data
      - hostPath:
          path: '{{ .Values.userspace.appData }}/mattermost/server-plugins'
          type: DirectoryOrCreate
        name: mattermost-server-plugins
      - hostPath:
          path: '{{ .Values.userspace.appData }}/mattermost/plugins'
          type: DirectoryOrCreate
        name: mattermost-plugins
---
apiVersion: v1
kind: Service
metadata:
  name: mattermost
  namespace: '{{ .Release.Namespace }}'
  labels:
    io.kompose.service: mattermost
spec:
  selector:
    io.kompose.service: mattermost
  type: ClusterIP
  ports:
  - port: 8065
    targetPort: http
    protocol: TCP
    name: mattermost
