---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firecrawl-config
  namespace: {{ .Release.Namespace }}
data:
  REDIS_URL: "redis://firecrawl-redis-svc:6379"
  REDIS_RATE_LIMIT_URL: "redis://firecrawl-redis-svc:6379"
  PLAYWRIGHT_MICROSERVICE_URL: "http://playwright-svc:3000/scrape"
  HOST: "0.0.0.0"
  PORT: "3002"
  USE_DB_AUTHENTICATION: "false"
  OPENAI_BASE_URL: {{ .Values.olaresEnv.OPENAI_BASE_URL | default "" | quote }}
  OLLAMA_BASE_URL: {{ .Values.olaresEnv.OLLAMA_BASE_URL | default "" | quote }}
  MODEL_NAME: {{ .Values.olaresEnv.MODEL_NAME | default "" | quote }}
  POSTHOG_API_KEY: ""
  NUQ_RABBITMQ_URL: "amqp://rabbitmq:5672"
  WORKER_PORT: "3005"
  EXTRACT_WORKER_PORT: "3004"
  NUQ_WORKER_PORT: "3006"
  NUQ_PREFETCH_WORKER_PORT: "3011"
  NUQ_WORKER_COUNT: "1"
  NUQ_PREFETCH_REPLICAS: "1"
  IS_KUBERNETES: "true"
  ENV: "production"
  NUM_WORKERS_PER_QUEUE: "8"
  LOGGING_LEVEL: "INFO"
  POSTGRES_HOST: "nuq-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "postgres"
