apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  namespace: "{{ .Release.Namespace }}"
  name: rabbitmq
spec:
  replicas: {{ .Values.workloads.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "docker.io/beclab/rabbitmq:3.13.7-management"
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 1Gi
              cpu: 1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
