image:
  repository: ghcr.io/progress44/rpi-system-chatterbox-tts
  tag: latest
  pullPolicy: Always

service:
  port: 8000

tts:
  model: turbo
  device: cuda
  enableDocs: "true"
  maxTextLength: "4000"
  defaultLanguage: en
  defaultAudioFormat: wav
  nvidiaVisibleDevices: all
  nvidiaDriverCapabilities: compute,utility
