---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hermesagent-config
  namespace: {{ .Release.Namespace }}
data:
  HERMES_HOME: /opt/hermes-home
  HOME: /home/node
  TERM: xterm-256color
  PATH: /opt/hermes/.venv/bin:/home/node/.local/bin:/usr/local/bin:/usr/bin:/bin
  NPM_CONFIG_PREFIX: /home/node/.npm-global
  API_SERVER_ENABLED: "0"
  HERMES_ENABLE_GATEWAY: "1"
  HERMES_ENABLE_API_SERVER: "0"
  HERMES_GATEWAY_RESTART_DELAY_SECONDS: {{ .Values.app.gatewayRestartDelaySeconds | quote }}
