---
apiVersion: v1
kind: Service
metadata:
  name: hermesagent
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: hermesagent
  ports:
    - name: dashboard
      protocol: TCP
      port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
    - name: gateway
      protocol: TCP
      port: {{ .Values.service.gatewayPort }}
      targetPort: {{ .Values.service.gatewayPort }}
