apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: novella
  name: novella
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: {{ .Values.workloads.novella.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: novella
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: novella
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            {{- $openaiKey := .Values.olaresEnv.CUSTOM_OPENAI_API_KEY | default .Values.olaresEnv.OPENAI_API_KEY }}
            {{- with $openaiKey }}
            - name: OPENAI_API_KEY
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.olaresEnv.OPENAI_BASE_URL }}
            - name: OPENAI_BASE_URL
              value: {{ . | quote }}
            {{- end }}
          image: "docker.io/beclab/harveyff-novel:v1.0.3"
          name: novella
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 4000Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: novella
  name: novella
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000

  selector:
    io.kompose.service: novella
