{{- $oe := .Values.olaresEnv | default dict -}}
{{- $val := $oe.SUNSHINE_PASS | default "" -}}
{{- if $val }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: steamheadless
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  SUNSHINE_PASS: {{ $val | quote }}
{{- end }}
