---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: penpot
spec:
  replicas: {{ .Values.workloads.penpot.replicaCount }}
  selector:
    matchLabels:
      app: penpot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: penpot
    spec:
      containers:
        - name: penpot
          image: "penpotapp/frontend:2.17"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/data/assets
              name: data-assets
          env:
            - name: PENPOT_FLAGS
              value: "enable-registration enable-login-with-password disable-email-verification enable-smtp enable-prepl-server enable-secure-session-cookies enable-mcp"
            - name: PENPOT_MCP_URI
              value: "http://penpot-mcp:4401"
            - name: PENPOT_MCP_URI_WS
              value: "http://penpot-mcp:4402"
            - name: PENPOT_EXPORTER_URI
              value: "http://penpot-exporter:6061"
            - name: PENPOT_BACKEND_URI
              value: "http://penpot-backend:6060"
      volumes:
        - name: data-assets
          hostPath:
            type: DirectoryOrCreate
            path: '{{ .Values.userspace.appData }}/data/assets'
