apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: bisheng
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "1234"
  MINIO_ROOT_PASSWORD: "minioadmin"
  BS_MINIO_ACCESS_KEY: "minioadmin"
  BS_MINIO_SECRET_KEY: "minioadmin"
