image:
  cpu:
    repository: quay.io/jupyter/base-notebook
    tag: "2025-12-31"
  nvidia:
    repository: beclab/jupyter-pytorch-notebook
    tag: "cuda13-notebook-7.6.0"
  pullPolicy: IfNotPresent

service:
  port: 8888

workloads:
  jupyternotebook:
    replicaCount: 1

resources:
  cpu:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "4"
      memory: 8Gi
  nvidia:
    requests:
      cpu: "1"
      memory: 8Gi
    limits:
      cpu: "8"
      memory: 20Gi
