---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rssubscribe-cluster-account
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rssubscribe-cluster-role
rules:
  - apiGroups:
      - '*'
    resources:
      - statefulsets
      - daemonsets
      - namespaces
      - serviceaccounts/token
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rssubscribe-cluster-binding
subjects:
  - kind: ServiceAccount
    name: rssubscribe-cluster-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: rssubscribe-cluster-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend:{{ .Release.Namespace }}:integration-provider-svc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backend:integration-provider-svc-cookie
subjects:
  - kind: ServiceAccount
    name: rssubscribe-cluster-account
    namespace: {{ .Release.Namespace }}
