{{- $rssubscribe_secret := (lookup "v1" "Secret" .Release.Namespace "rssubscribe-secrets") -}}
{{- $password := "" -}}
{{ if $rssubscribe_secret -}}
{{- $password = (index $rssubscribe_secret "data" "password") -}}
{{ else -}}
{{ $password = randAlphaNum 16 | b64enc }}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: rssubscribe-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PG_PASSWORD: {{ .Values.postgres.password | quote }}
data:
  password: {{ $password }}

---
apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: rssubscribe-nats
  namespace: {{ .Release.Namespace }}
spec:
  app: rssubscribe
  appNamespace: os
  middleware: nats
  nats:
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: rssubscribe-secrets
    user: "{{ .Release.Namespace }}-rssubscribe"
    subjects:
      - name: rssubscribe_status
        permission:
          pub: allow
          sub: allow
