apiVersion: v1
kind: Service
metadata:
  name: sandbox
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: sandbox
spec:
  selector:
    io.kompose.service: sandbox
  ports:
    - protocol: TCP
      port: 8194
      targetPort: 8194
      name: http 