{{- $oe := .Values.olaresEnv | default dict -}}
{{- $hfToken := $oe.HF_TOKEN | default "" -}}
{{- if $hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: '{{ .Release.Namespace }}'
type: Opaque
stringData:
  HF_TOKEN: {{ $hfToken | quote }}
{{- end }}
