apiVersion: v1
kind: Secret
metadata:
  name: hindsight-secrets
  namespace: "{{ .Release.Namespace }}"
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.postgres.username (.Values.postgres.password | urlquery) .Values.postgres.host .Values.postgres.port .Values.postgres.databases.hindsight | quote }}
  {{- $oe := .Values.olaresEnv | default dict }}
  {{- $apiKey := index $oe "HINDSIGHT_API_LLM_API_KEY" | default "not-required" }}
  {{- if $apiKey }}
  HINDSIGHT_API_LLM_API_KEY: {{ $apiKey | quote }}
  {{- end }}
