apiVersion: v1
kind: Service
metadata:
  name: hindsight-control-plane
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: hindsight-control-plane
spec:
  ports:
  - name: http
    port: 9999
    targetPort: 9999
  selector:
    app: hindsight-control-plane
