apiVersion: v1
kind: Service
metadata:
  name: hindsight
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: hindsight-api
    io.kompose.service: hindsight
spec:
  ports:
  - name: api
    port: 8888
    targetPort: 8888
  selector:
    io.kompose.service: hindsight
