{{- $old := lookup "v1" "Secret" .Release.Namespace "nextcloud-office" -}}
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-office
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ if and $old $old.data (index $old.data "JWT_SECRET") }}{{ index $old.data "JWT_SECRET" | b64dec | quote }}{{ else }}{{ randAlphaNum 64 | quote }}{{ end }}
  DB_PWD: {{ .Values.postgres.password | quote }}
  REDIS_SERVER_PASS: {{ .Values.redis.password | quote }}
  AMQP_PWD: {{ .Values.rabbitmq.password | quote }}
