image:
  repository: ghcr.io/progress44/rpi-system-kb-whisper-large
  tag: latest
  pullPolicy: Always

service:
  port: 8000

whisper:
  modelId: KBLab/kb-whisper-large
  device: cuda
  defaultLanguage: sv
  maxUploadSizeMb: "200"
  enableDocs: "true"
  nvidiaVisibleDevices: all
  nvidiaDriverCapabilities: compute,utility
