---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   creationTimestamp: null
#   labels:
#     io.kompose.service: chromium-claim0
#   name: chromium-claim0
#   namespace: {{ .Release.Namespace }}
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
# status: {}
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: chromium
  name: chromium
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      io.kompose.service: chromium
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: chromium
    spec:
      {{- $isOlaresOne := and .Values.deviceName (eq .Values.deviceName "Olares One") }}
      {{- $homepage := "https://www.google.com" }}
      {{- if and .Values.olaresEnv .Values.olaresEnv.CHROME_HOMEPAGE }}
      {{- $homepage = .Values.olaresEnv.CHROME_HOMEPAGE }}
      {{- end }}
      containers:
        - name: chromium
          image: "docker.io/beclab/harveyff-chromium:1e736296-ls34"
          {{- if $isOlaresOne }}
          securityContext:
            privileged: true
          {{- end }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: DeviceName
              value: {{ .Values.deviceName }}
            {{- if $isOlaresOne }}
            - name: CHROME_CLI
              value: "--ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --use-gl=egl --enable-features=UseOzonePlatform,VaapiVideoDecoder,VaapiVideoEncoder,CanvasOopRasterization,ReduceAcceptLanguageHeader {{ $homepage }}"
            - name: DRINODE
              value: /dev/dri/renderD128
            - name: DRI_NODE
              value: /dev/dri/renderD128
            - name: LIBVA_DRIVER_NAME
              value: iHD
            {{- else }}
            - name: CHROME_CLI
              value: {{ $homepage | quote }}
            - name: CHROME_FLAGS
              value: '--enable-features=ReduceAcceptLanguageHeader'
            {{- end }}
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 6Gi
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - containerPort: 3001
            {{- if $isOlaresOne }}
            - containerPort: 8082
            {{- end }}
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 3
            failureThreshold: 40
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /dev/shm
              name: dshm
            {{- if $isOlaresOne }}
            - mountPath: /dev/dri
              name: dev-dri
            {{- end }}
      restartPolicy: Always
      volumes:
        - name: config
          hostPath:
            type: DirectoryOrCreate
            {{- if .Values.sysVersion }}
              {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: {{ .Values.userspace.appCache }}/config
              {{- else }}
            path: {{ .Values.userspace.appCache }}/chromium/config
              {{- end }}
            {{- else }}
            path: {{ .Values.userspace.appCache }}/chromium/config
            {{- end }}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        {{- if $isOlaresOne }}
        - name: dev-dri
          hostPath:
            path: /dev/dri
        {{- end }}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: chromium
  name: chromium
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "3001"
      port: 3001
      targetPort: 3001
      nodePort: 30001
  selector:
    io.kompose.service: chromium
status:
  loadBalancer: {}
