{{- $homepage := "https://www.google.com" }}
{{- if and .Values.olaresEnv .Values.olaresEnv.CHROME_HOMEPAGE }}
{{- $homepage = .Values.olaresEnv.CHROME_HOMEPAGE }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chromium-policies
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: chromium
data:
  olares.json: |
    {
      "NewTabPageLocation": {{ $homepage | quote }},
      "DefaultSearchProviderEnabled": true,
      "DefaultSearchProviderName": "Google",
      "DefaultSearchProviderKeyword": "google.com",
      "DefaultSearchProviderSearchURL": "https://www.google.com/search?q={searchTerms}",
      "DefaultSearchProviderSuggestURL": "https://www.google.com/complete/search?output=chrome&q={searchTerms}",
      "DefaultSearchProviderIconURL": "https://www.google.com/favicon.ico",
      "DefaultSearchProviderEncodings": ["UTF-8"]
    }
