workloads:
  bisheng-redis:
    replicaCount: 1
  bisheng-mysql:
    replicaCount: 1
  milvus:
    replicaCount: 1
  bisheng:
    replicaCount: 1
  bisheng-backend-worker:
    replicaCount: 1
  bisheng-backend:
    replicaCount: 1
  bisheng-minio:
    replicaCount: 1
  bisheng-etcd:
    replicaCount: 1
  bisheng-es:
    replicaCount: 1
  bisheng-onlyoffice:
    replicaCount: 1
