{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-config
  namespace: {{ .Release.Namespace }}
data:
  CDN_HOST: "{{ .Values.olaresEnv.SYSTEM_CDN_SERVICE | default "https://cdn.olares.com" }}/gptoss/encodings"

{{- end }}