apiVersion: v1
kind: ConfigMap
metadata:
  name: bifrost-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "$schema": "https://www.getbifrost.ai/schema",
      "client": {
        "drop_excess_requests": false,
        "enable_logging": true
      },
      "config_store": {
        "enabled": true,
        "type": "postgres",
        "config": {
          "host": "{{ .Values.postgres.host }}",
          "port": "{{ .Values.postgres.port }}",
          "user": "{{ .Values.postgres.username }}",
          "password": "{{ .Values.postgres.password }}",
          "db_name": "{{ .Values.postgres.databases.bifrostdb }}",
          "ssl_mode": "disable",
          "max_idle_conns": 5,
          "max_open_conns": 50
        }
      },
      "logs_store": {
        "enabled": true,
        "type": "postgres",
        "config": {
          "host": "{{ .Values.postgres.host }}",
          "port": "{{ .Values.postgres.port }}",
          "user": "{{ .Values.postgres.username }}",
          "password": "{{ .Values.postgres.password }}",
          "db_name": "{{ .Values.postgres.databases.bifrostdb }}",
          "ssl_mode": "disable",
          "max_idle_conns": 5,
          "max_open_conns": 50
        }
      },
      "vector_store": {
        "enabled": true,
        "type": "redis",
        "config": {
          "addr": "{{ .Values.redis.host }}:{{ .Values.redis.port }}",
          "username": "",
          "password": "{{ .Values.redis.password }}",
          "db": 0,
          "pool_size": 10,
          "max_active_conns": 10,
          "min_idle_conns": 5,
          "max_idle_conns": 10
        }
      },
      "providers": {

      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bifrost-env
  namespace: {{ .Release.Namespace }}
data:
  OPENAI_API_KEY: ""
  # ANTHROPIC_API_KEY: ""