apiVersion: v1
kind: ConfigMap
metadata:
  name: md-nginx
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes auto;
    error_log /tmp/error.log warn;
    pid /tmp/nginx.pid;
    events {
      worker_connections 1024;
    }
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      sendfile on;
      keepalive_timeout 65;
      access_log /tmp/access.log;
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path /tmp/proxy_temp;
      fastcgi_temp_path /tmp/fastcgi_temp;
      uwsgi_temp_path /tmp/uwsgi_temp;
      scgi_temp_path /tmp/scgi_temp;
      server {
        listen 8080;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        location / {
          try_files $uri $uri/ /index.html;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: md
spec:
  replicas: {{ .Values.workloads.md.replicaCount }}
  selector:
    matchLabels:
      app: md
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: md
    spec:
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: md
          image: doocs/md:2.1.0-nginx
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Etc/UTC"
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: nginx-config
          configMap:
            name: md-nginx
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: md-svc
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: md
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 8080
      protocol: TCP
  selector:
    app: md
status:
  loadBalancer: {}
