apiVersion: v1
kind: ConfigMap
metadata:
  name: koboldcpp-env
  namespace: {{ .Release.Namespace }}
data:
  NVIDIA_VISIBLE_DEVICES: "all"
  NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
  KCPP_MODEL: ""
  KCPP_ARGS: "--model /models/Qwen3.5-4B-UD-Q4_K_XL.gguf --contextsize 4096 --usecuda --gpulayers 99 --mmproj /models/mmproj-F32.gguf --sdmodel /models/picX_real.safetensors --sdquant 1 --whispermodel /models/ggml-large-v3-turbo.bin --ttsmodel /models/Qwen3-TTS-12Hz-1.7B-Base-q8_0.gguf --ttswavtokenizer /models/qwen3-tts-tokenizer-q8_0.gguf --ttsgpu --admin --admindir /models/admindir"
  KCPP_DONT_UPDATE: "true"
  KCPP_DONT_TUNNEL: "true"
  KCPP_DONT_REMOVE_MODELS: "true"
