workloads:
  traefik:
    replicaCount: 1
  chain-client-solana-solana-501:
    replicaCount: 1
  metrics:
    replicaCount: 1
  metrics-hub:
    replicaCount: 1
  amm-market-price:
    replicaCount: 1
  otmoiclp:
    replicaCount: 1
  amm-graphql:
    replicaCount: 1
  chain-client-evm-op-614:
    replicaCount: 1
  chain-client-evm-eth-60:
    replicaCount: 1
  chain-client-evm-bsc-9006:
    replicaCount: 1
  lpnode-dashboard:
    replicaCount: 1
  amm-amm-01-analyze:
    replicaCount: 1
  amm-amm-01:
    replicaCount: 1
  lpnode-admin:
    replicaCount: 1
