apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tensorzero
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: "chpassword"
  TENSORZERO_POSTGRES_URL: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgres.username .Values.postgres.password .Values.postgres.host (.Values.postgres.port | toString) .Values.postgres.databases.tensorzero | quote }}
