---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: {{ .Values.workloads.lobechat.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      containers:
        - name: lobechat
          image: "docker.io/lobehub/lobehub:2.1.39"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: lobechat-config
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: DATABASE_URL
            - name: KEY_VAULTS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: KEY_VAULTS_SECRET
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: AUTH_SECRET
          ports:
            - name: http
              containerPort: 3210
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 3210
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 3210
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 200m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3210
  selector:
    app: "{{ .Release.Name }}"
