apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: lobechat
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.databases.lobechat }}"
  KEY_VAULTS_SECRET: "jgwsK28dspyVQoIf8/M3IIHl1h6LYYceSYNXeLpy6uk="
  AUTH_SECRET: "jgwsK28dspyVQoIf8/M3IIHl1h6LYYceSYNXeLpy6uk="
