apiVersion: v1
kind: ConfigMap
metadata:
  name: excalidraw-nginx
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes auto;
    pid /tmp/nginx.pid;
    error_log /dev/stderr warn;
    events { worker_connections 1024; }
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        access_log /dev/stdout;
        sendfile on;
        keepalive_timeout 65;
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path /tmp/proxy_temp;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        scgi_temp_path /tmp/scgi_temp;
        server {
            listen 8080;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;
            location / { try_files $uri $uri/ /index.html; }
            location ~* \.(?:js|css|woff2?|png|svg|ico|webmanifest)$ {
                try_files $uri =404;
            }
        }
    }
