{{- $pgPort := .Values.postgres.port | default "5432" | toString -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: memos
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  MEMOS_DSN: {{ printf "postgres://%s:%s@%s:%s/%s?sslmode=disable" (.Values.postgres.username | toString) (.Values.postgres.password | toString) (.Values.postgres.host | toString) $pgPort (.Values.postgres.databases.memosdb | toString) | quote }}
