apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  GITEA__database__PASSWD: {{ .Values.postgres.password | toString | quote }}
