userspace:
  appdata: ""
  appCache: ""

timezone: Etc/UTC

rtspPassword: frigate

cacheSize: 4Gi

shmSize: 2Gi

securityContext:
  privileged: false

usb:
  enabled: false

resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 4000m
    memory: 5Gi

workloads:
  frigate:
    replicaCount: 1
