apiVersion: v2
name: syncthing
description: Syncthing is a continuous file synchronization program. It synchronizes files between two or more computers in real time.
type: application
version: 1.0.1
appVersion: "2.1.1"
