{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
{{- $ollamaclientDomainENV := split "," .Values.domain.ollamaclient -}}
{{- $ollamaclientDomain := index $ollamaclientDomainENV "_0" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-env
  namespace: "{{ .Release.Namespace }}"
data:
  PGID: "1000"
  PUID: "1000"
  TZ: "Etc/UTC"
  GGML_CUDA_DISABLE_GRAPHS: "1"
  OLLAMA_ORIGINS: "*"
  OLLAMA_DEBUG: "1"
  MODEL_NAME: "qwen3.5:27b-q4_K_M"
  OLLAMA_CONTEXT_LENGTH: "32768"
  OLLAMA_NUM_PARALLEL: "1"
  OLLAMA_FLASH_ATTENTION: "1"
  OLLAMA_KV_CACHE_TYPE: "q8_0"
{{- end }}
