apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: router-catalog-nats
  namespace: {{ .Release.Namespace }}
spec:
  app: router
  appNamespace: router
  middleware: nats
  nats:
    user: os-router
    password:
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-secrets
          key: LLM_GATEWAY_CATALOG_EVENTS_NATS_PASS
    subjects:
      - name: catalog
        permission:
          pub: allow
          sub: deny
        export:
          - appName: mins
            pub: deny
            sub: allow
