---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: router-cluster-view:lldap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backend:lldap-provider
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: router-cluster-view:market
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backend:market-provider
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: router-tokenrequest
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: router-tokenrequest
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: router-tokenrequest
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: router-role
rules:
  - apiGroups:
      - sys.bytetrade.io
    resources:
      - systemenvs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - iam.kubesphere.io
    resources:
      - users
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - app.bytetrade.io
    resources:
      - applicationmanagers
      - applications
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: router-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: router-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "{{ .Release.Namespace }}"
