image:
  repository: docker.io/beclab/audio-speakrs
  tag: sha-48adf68
  pullPolicy: IfNotPresent

llminit:
  repository: docker.io/beclab/llm-init
  tag: v1.7.16
  pullPolicy: IfNotPresent

model:
  source: hf://avencera/speakrs-models --exclude *.mlmodelc/*
  engineArgs: ""
  executionMode: cuda

hf:
  endpoint: https://huggingface.co/

logLevel: info

workloads:
  audiospeakrsdiarv3:
    replicaCount: 1
  llminit:
    replicaCount: 1

userspace:
  appData: /tmp/audiospeakrsdiarv3-appdata
  appCache: /tmp/audiospeakrsdiarv3-appcache
  appCommon: /tmp/audiospeakrsdiarv3-appcommon
