apiVersion: v2
appVersion: "2.0.2"
description: DeepSeek-OCR-WebUI is an intelligent image recognition web application based on the DeepSeek-OCR-2 model
name: deepseekocrwebuiv2
type: application
version: "1.0.5"
