apiVersion: v2
name: ollamaniemotron3nano30ba3bserver
description: Server component for Nemotron-3-Nano 30B A3B (Ollama) model

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.30.4"